server:
  # 服务端口号
  port: 8081

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.138.155.114:9090/hjqdm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: hjqdmhh
    password: 7Drfjjz&9u@Dfx3C

# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
